version: '3.3'
services:
  client:
    image: client:latest
    ports:
     - "80:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
     - "./client:/usr/src/app"
  server:
    image: server:latest
    ports:
     - "8000:80"
    volumes:
     - "./server:/var/www"