const types = {
  UPLOAD_DOCUMENT: '@@kraken/UPLOAD_DOCUMENT',
  ON_DOCUMENT_UPLOAD: '@@kraken/ON_DOCUMENT_UPLOAD',
  DELETE_DOCUMENT: '@@kraken/DELETE_DOCUMENT',
  ON_DOCUMENT_DELETE: '@@kraken/ON_DOCUMENT_DELETE',
  GET_DOCUMENTS: '@@kraken/GET_DOCUMENTS',
  ON_GET_DOCUMENTS: '@@kraken/ON_GET_DOCUMENTS',
  ON_FILE_SUBMIT_CHANGED: '@@kraken/ON_FILE_SUBMIT_CHANGED'
}

export default types
